### ISSUE TITLE
transition: pkg-config to pkgconf

### ISSUE THREAD

**Issue by UTsweetyfish** [deepin-community/pkgconf#1]
llvm-toolchain-14 构建中出现了 pkg-config 与 pkgconf 出现冲突的情况，考虑使用 pkgconf 替换 pkg-config。

> pkgconf is a newer, actively maintained implementation of pkg-config that
> supports more aspects of the pkg-config file specification and provides a
> library interface that applications can use to incorporate intelligent
> handling of pkg-config files into themselves (such as build file generators,
> IDEs, and compilers).
>
> pkgconf is compatible with pkg-config when it is run as "pkg-config", so it
> can completely replace the original implementation.

[Transition proposal: pkg-config to pkgconf](https://lists.debian.org/debian-devel/2022/07/msg00252.html), (view thread on [googlegroups](https://groups.google.com/g/linux.debian.devel/c/kmS6iIcClPY))
[DebConf 22 pkg-config / pkgconf BoF](https://debconf22.debconf.org/talks/86-pkg-config-pkgconf-bof/)

考虑等待 https://github.com/deepin-community/rfcs/pull/4 合并后进行 pkg-config 的退出流程。

## 目前对软件包做出的修改

- grpc: debian 在 d/control 里使用了 pkgconf。检查代码后发现无兼容性问题，因此放宽了限制 (https://github.com/deepin-community/grpc/pull/5)

/cc @deepin-community/deepin-sysdev-team @chenchongbiao

**Comment by chenchongbiao** [comment]
1
